### ISSUE TITLE
transfer documentation jira ticket to github

### ISSUE THREAD

**Issue by dlamoris** [Open-MBEE/open-mbee.github.io#37]
transfer epic and tickets
https://openmbee.atlassian.net/browse/OMBEE-28

**Comment by lewismc** [comment]
@dlamoris same with this one. Is this still valid or can this be closed off? Thanks

**Comment by dlamoris** [comment]
i think this can be closed, it's a general one about going through all the scattered documentation, i'll keep a note of the links in that jira

**Comment by lewismc** [comment]
OK thanks
