### ISSUE TITLE
Remove or overhaul Roadmap

### ISSUE THREAD

**Issue by lewismc** [Open-MBEE/open-mbee.github.io#60]
The [roadmap](https://www.openmbee.org/roadmap.html#) is outdated, confusing and ultimat4ly useless. We need to either update it or remove it entirely.

**Comment by lewismc** [comment]
@dlamoris @HuiJun with regards to the roadmap, I propose that we remove it entirely and/or replace it with a hyperlink to the [active projects](https://github.com/orgs/Open-MBEE/projects)... which should mostly be OEP's.
Any thoughts? Thanks

**Comment by dlamoris** [comment]
sounds good to me
